check for more than one label

diff --git a/.github/workflows/protect-main.yaml b/.github/workflows/protect-main.yaml
--- a/.github/workflows/protect-main.yaml
+++ b/.github/workflows/protect-main.yaml
@@ -32,6 +32,11 @@ jobs:
       - name: Set PR_LABEL environment variable 
         run: |
             PR_LABEL_JSON='${{ toJson(github.event.pull_request.labels.*.name) }}'
+            LABEL_COUNT=$(echo $PR_LABEL_JSON | jq 'length')
+            if [ $LABEL_COUNT -ne 1 ]; then
+              echo "Error: More than one label is not allowed."
+              exit 1
+            fi
             PR_LABEL=$(echo $PR_LABEL_JSON | jq -r '.[0]')
             echo $PR_LABEL
             echo "PR_LABEL=$PR_LABEL" >> $GITHUB_ENV
@@ -63,12 +68,18 @@ jobs:
               patch = match.group(3)
               pr_label = os.getenv('PR_LABEL')
               print(f'PR Label: {pr_label}')
-              if pr_label == 'Major Version':
-                  major = int(major) + 1
-              elif pr_label == 'Minor Version':
-                  minor = int(minor) + 1
-              elif pr_label == 'Bugfix Version':
-                  patch = int(patch) + 1
+              if pr_label:
+                if pr_label == 'Major Version':
+                    major = int(major) + 1
+                elif pr_label == 'Minor Version':
+                    minor = int(minor) + 1
+                elif pr_label == 'Bugfix Version':
+                    patch = int(patch) + 1
+              else:
+                if '${{ env.GH_ISSUE_TYPE }}' == 'FEATURE':
+                    minor = int(minor) + 1
+                elif '${{ env.GH_ISSUE_TYPE }}' == 'BUGFIX':
+                    patch = int(patch) + 1
           
               new_version = f'{major}.{minor}.{patch}'
               with open(version_file, 'w') as file:
