remove eof lines'

diff --git a/.github/workflows/TQA-118.yml b/.github/workflows/TQA-118.yml
--- a/.github/workflows/TQA-118.yml
+++ b/.github/workflows/TQA-118.yml
@@ -36,8 +36,12 @@ jobs:
       - name: Read NEWS.rst
         id: read_release_notes
         run: |
-          RELEASE_NOTES=$(NEWS.rst)
-          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
+          if [ ! -f "NEWS.rst" ]; then
+            echo "ERROR: NEWS.rst file not found!"
+            exit 1
+          fi
+          echo "${RELEASE_NOTES}" >> $GITHUB_ENV
+
 
       - name: Read version from VERSION.txt
         id: read_version
@@ -57,29 +61,31 @@ jobs:
           draft: false
           prerelease: false
 
-      # - name: Clear contents of NEWS.rst and newsfragments
-      #   run: | 
-      #     echo '' > NEWS.rst
+      - name: Clear contents of NEWS.rst and newsfragments
+        run: | 
+          rm -rf newsfragments/!(.gitignore)
+          echo '' > NEWS.rst
 
-      # - name: Commit and Push Empty NEWS.rst
-      #   uses: EndBug/add-and-commit@v9
-      #   with:
-      #     ref: ${{ github.event.pull_request.head.ref }}
-      #     add: '["NEWS.rst", "newsfragments"]'
-      #     author_name: 'Github Actions - Release Notes Workflow'
-      #     author_email: actions@github.com
-      #     commit: --signoff
-      #     committer_name: 'Github Actions - Release Notes Workflow'
-      #     committer_email: actions@github.com
-      #     cwd: "."
-      #     default_author: github_actor
-      #     fetch: true
-      #     message: "Clear contents of NEWS.rst and newsfragments"
-      #     pathspec_error_handling: exitImmediately
-      #     push: true
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
-      #     message: "Clear contents of NEWS.rst and newsfragments"
-      #     pathspec_error_handling: exitImmediately
-      #     push: true
+
+      - name: Commit and Push Empty NEWS.rst
+        uses: EndBug/add-and-commit@v9
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          add: '["NEWS.rst", "newsfragments"]'
+          author_name: 'Github Actions - Release Notes Workflow'
+          author_email: actions@github.com
+          commit: --signoff
+          committer_name: 'Github Actions - Release Notes Workflow'
+          committer_email: actions@github.com
+          cwd: "."
+          default_author: github_actor
+          fetch: true
+          message: "Clear contents of NEWS.rst and newsfragments"
+          pathspec_error_handling: exitImmediately
+          push: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
+          message: "Clear contents of NEWS.rst and newsfragments"
+          pathspec_error_handling: exitImmediately
+          push: true
       
